[package]
name = "atlas-local"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/mongodb/atlas-local-cli/"

[features]
default = []
e2e-tests = []
generate-manifest = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
dialoguer = "0.12.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
