[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Features to pass to cargo build
features = ["generate-manifest"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "upload"
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["manifest.yml", "LICENSE", "LICENSE-3RD-PARTY.txt"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Whether to use cargo-cyclonedx to generate an SBOM
cargo-cyclonedx = true
# Publish jobs to run in CI
publish-jobs = ["./sign-zip"]

[dist.dependencies.apt]
libdbus-1-dev = '*'
